from config.base import Base
from sqlalchemy import Column, Integer, Numeric, String



class Mission(Base):
    __tablename__ = 'mission'

    mission_id = Column(Integer, primary_key=True)
    mission_date = Column(String)  # Adjust to Date type if needed
    theater_of_operations = Column(String(100))
    country = Column(String(100))
    air_force = Column(String(100))
    unit_id = Column(String(100))
    aircraft_series = Column(String(100))
    callsign = Column(String(100))
    mission_type = Column(String(100))
    takeoff_base = Column(String(255))
    takeoff_location = Column(String(255))
    takeoff_latitude = Column(String(15))
    takeoff_longitude = Column(Numeric(10, 6))
    target_id = Column(String(100))
    target_country = Column(String(100))
    target_city = Column(String(100))
    target_type = Column(String(100))
    target_industry = Column(String(255))
    target_priority = Column(String(5))
    target_latitude = Column(Numeric(10, 6))
    target_longitude = Column(Numeric(10, 6))
    altitude_hundreds_of_feet = Column(Numeric(7, 2))
    airborne_aircraft = Column(Numeric(4, 1))
    attacking_aircraft = Column(Integer)
    bombing_aircraft = Column(Integer)
    aircraft_returned = Column(Integer)
    aircraft_failed = Column(Integer)
    aircraft_damaged = Column(Integer)
    aircraft_lost = Column(Integer)
    high_explosives = Column(String(255))
    high_explosives_type = Column(String(255))
    high_explosives_weight_pounds = Column(String(25))
    high_explosives_weight_tons = Column(Numeric(10, 2))
    incendiary_devices = Column(String(255))
    incendiary_devices_type = Column(String(255))
    incendiary_devices_weight_pounds = Column(Numeric(10, 2))
    incendiary_devices_weight_tons = Column(Numeric(10, 2))
    fragmentation_devices = Column(String(255))
    fragmentation_devices_type = Column(String(255))
    fragmentation_devices_weight_pounds = Column(Numeric(10, 2))
    fragmentation_devices_weight_tons = Column(Numeric(10, 2))
    total_weight_pounds = Column(Numeric(10, 2))
    total_weight_tons = Column(Numeric(10, 2))
    time_over_target = Column(String(8))
    bomb_damage_assessment = Column(String(255))
    source_id = Column(String(100))
